baseURL = 'https://example.org/'

title = '我的博客'
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'


#[markup]
#  _merge = "shallow"
#[outputs]
#  _merge = "shallow"
#[taxonomies]
#  _merge = "shallow"

