baseURL = 'https://example.org/'

title = 'My New Hugo Site'
theme = 'FixIt'
defaultContentLanguage = 'zh-cn'


#[markup]
#  _merge = "shallow"
#[outputs]
#  _merge = "shallow"
#[taxonomies]
#  _merge = "shallow"

