# -------------------------------------------------------------------------------------
# 主题核心配置
# -------------------------------------------------------------------------------------

# FixIt 主题版本
version = "0.2.X"
# 网站描述，用于 RSS, SEO, Open Graph 和 Twitter Cards
description = "A Clean, Elegant but Advanced Hugo Theme FixIt"
# 网站关键词
keywords = ["Linux", "docker", "vps", "个人博客"]
# 网站默认主题 ["light", "dark", "auto"]
defaultTheme = "auto"
# 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
# 日期格式
dateFormat = "2006-01-02"
# 网站图片，用于 Open Graph 和 Twitter Cards
images = ["/images/apple-devices-preview.webp"]
# FixIt 0.2.12 | 新增 开启 PWA 支持
enablePWA = true
# FixIt 0.2.14 | 新增 是否自动显示外链图标
externalIcon = true
# FixIt 0.3.13 | 新增 是否大写标题
capitalizeTitles = true
# FixIt 0.3.0 | 新增 是否在每个页面标题中添加网站标题
# 请记得在 `hugo.toml` 中设置网站标题 (例如 title = "title")
withSiteTitle = true
# FixIt 0.3.0 | 新增 当网站标题被添加到每个页面标题时的标题分隔符
titleDelimiter = "|"
# FixIt 0.3.0 | 新增 是否在主页标题中添加网站副标题
# 请记得通过 `params.header.subtitle.name` 设置网站副标题
indexWithSubtitle = true
# FixIt 0.3.13 | 新增 是否显示纯文本摘要
summaryPlainify = true 
# FixIt 0.2.14 | 新增 默认情况下，FixIt 只会在主页的 HTML 头中注入主题元标记。
# 您可以将其关闭，但如果您不这样做，我们将不胜感激，因为这是观察 FixIt 受欢迎程度上升的好方法。
disableThemeInject = false

# 作者配置
[author]
  name = "ifun"
  email = "ifun@azfum.com"
  link = "https://www.azfum.com"
  avatar = "/images/avatar.webp"

# 应用图标配置
[app]
  # 当添加到 iOS 主屏幕或者 Android 启动器时的标题，覆盖默认标题
  title = "azfum"
  # 是否隐藏网站图标资源链接
  noFavicon = false
  # 更现代的 SVG 网站图标，可替代旧的 .png 和 .ico 文件
  # svgFavicon = "/images/fixit.min.svg"
  # Safari 图标颜色
  iconColor = "#FF7359"
  # Windows v8-10 磁贴颜色
  tileColor = "#2d89ef"
  # Android 浏览器主题色
  [app.themeColor]
    light = "#f8f8f8"
    dark = "#252627"

# 搜索配置
[search]
  enable = true
  # 搜索引擎的类型 ["algolia", "fuse", "cse"]
  type = "fuse"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = ""
  # 最大结果数目
  maxResultLength = 10
  # 结果内容片段长度
  snippetLength = 30
  # 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [search.algolia]
    index = ""
    appID = "YKOM6PKLUY"
    searchKey = "a44c110d3ac360be2c69cd79d34b77a8"
  [search.fuse]
    # FixIt 0.2.17 | 新增 https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

# FixIt 0.3.16 | 新增 自定义搜索引擎 (CSE)
[cse]
  # 搜索引擎：["google", "bing"]
  engine = "google"
  # 搜索结果页面 URL (layout: search)
  resultsPage = "/search/"
  # Google 自定义搜索引擎 ID
  [cse.google]
    cx = ""
  [cse.bing]

# 页面头部导航栏配置
[header]
  # 桌面端导航栏模式 ["sticky", "normal", "auto"]
  desktopMode = "sticky"
  # 移动端导航栏模式 ["sticky", "normal", "auto"]
  mobileMode = "auto"
  # 页面头部导航栏标题配置
  [header.title]
    # LOGO 的 URL，默认为网站图标
    logo = "/images/logo.png"
    # 标题名称，默认为网站标题
    name = ""
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息，例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息，例如图标
    post = ""
    # 是否为标题显示打字机动画
    typeit = false
  # FixIt 0.2.12 | 新增 页面头部导航栏副标题配置
  [header.subtitle]
    # 副标题名称
    name = ""
    # 是否为副标题显示打字机动画
    typeit = false

# FixIt 0.2.18 | 新增 面包屑导航配置
[breadcrumb]
  enable = true
  sticky = true
  showHome = false
  # FixIt 0.3.13 | 新增 分隔符
  separator = "/"
  capitalize = true

# FixIt 0.3.10 | 新增 文章导航配置
[navigation]
  # 是否在 section 页面范围内显示文章导航
  inSection = false
  # 是否反转 下一篇/上一篇 文章导航顺序
  reverse = false

# 页面底部信息配置
[footer]
  enable = true
  # 是否显示版权信息
  copyright = true
  # 是否显示作者
  author = false
  # 网站创立年份
  since = 2021
  # TODO 是否显示网站内容总字数
  wordCount = true
  # FixIt 0.2.12 | 新增 公网安备信息，仅在中国使用 (支持 HTML 格式)
  gov = ""
  # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
  icp = ""
  # 许可协议信息 (支持 HTML 格式)
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # FixIt 0.3.0 | 新增 是否显示 Hugo 和主题信息
  [footer.powered]
    enable = true
    hugoLogo = false
    themeLogo = false
  # FixIt 0.2.17 | 更改 网站创立时间
  [footer.siteTime]
    enable = true
    animate = true
    icon = "fa-solid fa-heartbeat"
    pre = ""
    value = "2021-12-18T16:15:22+08:00"
  # FixIt 0.2.17 | 新增 页面底部行排序，可选值：["first", 0, 1, 2, 3, 4, 5, "last"]
  [footer.order]
    powered = 0
    copyright = 0
    statistics = 0
    visitor = 0
    beian = 0


# Section (所有文章) 页面配置
[section]
  # section 页面每页显示文章数量
  paginate = 20
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # FixIt 0.3.10 | 新增 Section feed 配置用于 RSS, Atom 和 JSON feed。
  [section.feed]
    # 包含在 feed 中的文章数目。如果设置为 -1，代表所有文章。
    limit = -1
    # 是否在 feed 中显示全文内容。
    fullText = false

# List (目录或标签) 页面配置
[list]
  # list 页面每页显示文章数量
  paginate = 20
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # FixIt 0.3.10 | 新增 Term list feed 配置用于 RSS, Atom 和 JSON feed。
  [list.feed]
    # 包含在 feed 中的文章数目。如果设置为 -1，代表所有文章。
    limit = -1
    # 是否在 feed 中显示全文内容。
    fullText = false

# FixIt 0.3.13 | 新增 最近更新页面配置用于归档、section 和 term 列表
[recentlyUpdated]
  archives = true
  section = true
  term = true
  days = 30
  maxCount = 10

# 标签云配置
[tagcloud]
  enable = true
  # 以 px 为单位的最小字体大小
  min = 14
  # 以 px 为单位的最大字体大小
  max = 32
  # 每个标签的最大帖子数
  peakCount = 10
  # 标签顺序，可选值：["name", "count"]
  orderby = "name"

# 主页配置
[home]
  # RSS 文章数目
  rss = 10
  # 主页个人信息
  [home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "/images/avatar.webp"
    # FixIt 0.2.17 | 新增 头像菜单链接的 identifier
    avatarMenu = ""
    # 主页显示的网站标题（支持 HTML 格式）
    title = ""
    # 主页显示的网站副标题
    subtitle = "This is my new Hugo FixIt site"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # 免责声明（支持 HTML 格式）
    disclaimer = ""
  # 主页文章列表
  [home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6

# FixIt 0.2.15 | 新增 Mermaid 配置
[mermaid]
  # 取值详见 https://mermaid.js.org/config/theming.html#available-themes
  themes = ["default", "dark"]

# FixIt 0.3.13 | 新增 自定义 Admonition 配置
# 语法: <type> = <icon>
# 详见 https://fixit.lruihao.cn/documentation/content-management/shortcodes/extended/admonition/#custom-admonitions
[admonition]
  ban = "fa-solid fa-ban"
  sponsor = "fa-solid fa-hand-holding-usd"

# FixIt 0.3.14 | 新增 自定义任务列表配置
# 语法: <sign> = <icon>
# 详见 https://fixit.lruihao.cn/documentation/content-management/advanced/#custom-task-lists
[taskList]
  tip = "fa-regular fa-lightbulb"



# FixIt 0.2.12 | 新增 水印配置
# 详细参数见 https://github.com/Lruihao/watermark#readme
[watermark]
  enable = true
  # 水印内容 (允许 HTML 格式)
  content = ""
  # 水印透明度
  opacity = 0.0125
  # 单水印宽度 单位：px
  width = 150
  # 单水印高度 单位：px
  height = 21
  # 水印行间距 单位：px
  rowSpacing = 60
  # 水印列间距 单位：px
  colSpacing = 30
  # 水印旋转角度 单位：deg
  rotate = 15
  # 水印字体大小，单位：rem
  fontSize = 0.85
  # 水印字体
  fontFamily = "inherit"

# FixIt 0.3.10 | 新增 不蒜子计数
[busuanzi]
  # 是否启用不蒜子计数
  enable = true
  # 不蒜子计数器核心脚本地址。默认为 https://vercount.one/js
  source = "https://vercount.one/js"
  # 是否显示网站访问量
  siteViews = true
  # 是否显示页面访问量
  pageViews = true

# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu/360/Sogou
[verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""
  so = ""
  sogou = ""

# 网站 SEO 配置
[seo]
  # 图片 URL
  image = "/images/apple-devices-preview.webp"
  # 缩略图 URL
  thumbnailUrl = "/images/tn.webp"


# 网站分析配置
[analytics]
  enable = false
  # Google Analytics
  [analytics.google]
    id = ""
    # 是否匿名化用户 IP
    anonymizeIP = true
  # Fathom Analytics
  [analytics.fathom]
    id = ""
    # 自行托管追踪器时的主机路径
    server = ""
  # FixIt 0.3.16 | 新增 百度统计
  [analytics.baidu]
    id = ""
  # FixIt 0.3.16 | 新增 Umami 统计
  [analytics.umami]
    data_website_id = ""
    src = ""
    data_host_url = ""
    data_domains = ""
  # FixIt 0.3.16 | 新增 Plausible 统计
  [analytics.plausible]
    data_domain = ""
    src = ""
  # FixIt 0.3.16 | 新增 Cloudflare 统计
  [analytics.cloudflare]
    token = ""
  # FixIt 0.3.16 | 新增 Splitbee 统计
  [analytics.splitbee]
    enable = false
    # 无 Cookie 模式
    no_cookie = true
    # 遵循浏览器的“请勿跟踪”设置
    do_not_track = true
    # token（可选），详细信息见 https://splitbee.io/docs/embed-the-script
    data_token = ""

# Cookie 许可配置
[cookieconsent]
  enable = true
  # 用于 Cookie 许可横幅的文本字符串
  [cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

# 第三方库文件的 CDN 设置
[cdn]
  # CDN 数据文件名称，默认不启用 ["jsdelivr.yml", "unpkg.yml", ...]
  # 位于 "themes/FixIt/assets/data/cdn/" 目录
  # 可以在你的项目下相同路径存放你自己的数据文件："assets/data/cdn/"
  # data = "unpkg.yml"

# FixIt 0.2.14 | 新增 Gravatar 设置
# 详细见 https://docs.gravatar.com/general/images/
[gravatar]
  # FixIt 0.2.18 | 新增 取决于作者邮箱，作者邮箱未设置则使用本地头像
  enable = true
  # Gravatar 主机，默认：“www.gravatar.com”
  host = "gravatar.loli.net" # ["cravatar.cn", "gravatar.loli.net", ...]
  style = "mp" # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]

# 返回顶部
[backToTop]
  enable = true
  # 在返回顶部按钮中显示滚动百分比
  scrollpercent = true

# 阅读进度条配置
[readingProgress]
  enable = true
  # 可用值：["left", "right"]
  start = "left"
  # 可用值：["top", "bottom"]
  position = "top"
  reversed = false
  light = "#000"
  dark = "#fff"
  height = "2px"

# FixIt 0.2.17 | 新增 页面加载期间顶部的进度条
# 有关详细信息：https://github.com/CodeByZach/pace
[pace]
  enable = true
  # 所有可用颜色：
  # ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
  color = "blue"
  # 所有可用主题：
  # ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
  # "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
  theme = "minimal"

# 文章页面配置
[page]
  # FixIt 0.2.18 | 新增 是否启用文章作者头像
  authorAvatar = true
  # 是否在主页隐藏一篇文章
  hiddenFromHomePage = false
  # 是否在搜索结果中隐藏一篇文章
  hiddenFromSearch = false
  # FixIt 0.3.0 | 新增 是否在 RSS 中隐藏一篇文章
  hiddenFromFeed = false
  # FixIt 0.3.0 | 新增 是否在相关文章中隐藏一篇文章
  hiddenFromRelated = false
  # 是否使用 twemoji
  twemoji = false
  # FixIt 0.2.18 | 更改 是否使用 lightgallery
  # 设为 true，且图片设置标题时，文章中的图片将以画廊形式呈现，例如：![alt](src "title")
  # 设为 "force"，无论图片是否设置标题文章中的图片都将强制按照画廊形式呈现，例如：![alt](src)
  lightgallery = false
  # 是否使用 ruby 扩展语法
  ruby = true
  # 是否使用 fraction 扩展语法
  fraction = true
  # 是否使用 fontawesome 扩展语法
  fontawesome = true
  # 许可协议信息（支持 HTML 格式）
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
  # 是否显示原始 Markdown 文档内容的链接
  linkToMarkdown = false
  # 是否显示查看文章源码的链接
  linkToSource = false
  # 是否显示编辑文章的链接
  linkToEdit = false
  # 是否显示报告文章问题的链接
  linkToReport = false
  # FixIt 0.3.10 | 更改 页面样式 ["narrow", "normal", "wide", ...]
  pageStyle = "normal"
  # FixIt 0.2.17 | 更改 自动书签支持
  # 如果为 true，关闭页面时保存阅读进度。
  autoBookmark = false
  # FixIt 0.2.17 | 新增 是否启用字数显示
  wordCount = true
  # FixIt 0.2.17 | 新增 是否开启预计阅读时间显示
  readingTime = true
  # 文章结束标志
  endFlag = ""
  # FixIt 0.2.18 | 新增 是否开启即时页面
  instantPage = true
  # FixIt 0.3.0 | 新增 是否在侧边栏显示集合列表
  collectionList = false
  # FixIt 0.3.0 | 新增 是否在文章末尾显示集合导航
  collectionNavigation = true
  # FixIt 0.2.15 | 新增 转载配置
  [page.repost]
    enable = false
    url = ""
  # 目录配置
  [page.toc]
    # 是否使用目录
    enable = true
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = true
    # FixIt 0.2.13 | 新增 目录位置 ["left", "right"]
    position = "right"
    # FixIt 0.3.12 | 新增 取代 `markup.tableOfContents` 设置
    ordered = false
    startLevel = 2
    endLevel = 6


# 文章过期提醒配置
[page.expirationReminder]
  enable = true
  # 提醒：文章最后更新超过 90 天时显示提示
  reminder = 90
  # 警告：文章最后更新超过 180 天时显示警告
  warning = 180
  # 是否因文章到期而关闭评论
  closeComment = false

# 页面标题和标题编号配置
[page.heading]
  # 是否自动大写标题文本
  capitalize = true
  # 标题自动编号设置
  [page.heading.number]
    enable = true
    onlyMainSection = true
    # 各级标题的编号格式
    [page.heading.number.format]
      h1 = "{title}"
      h2 = "{h2} {title}"
      h3 = "{h2}.{h3} {title}"
      h4 = "{h2}.{h3}.{h4} {title}"
      h5 = "{h2}.{h3}.{h4}.{h5} {title}"
      h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"

# 代码块包装器配置
[page.code]
  enable = true
  copy = true
  edit = true
  # 默认展开显示的代码行数
  maxShownLines = 10

# 数学公式配置 (KaTeX https://katex.org/)
[page.math]
  enable = false
  inlineLeftDelimiter = ""
  inlineRightDelimiter = ""
  blockLeftDelimiter = ""
  blockRightDelimiter = ""
  copyTex = true
  mhchem = true

# 缓存远程图片到本地 (实验性功能)
[page.cacheRemoteImages]
  enable = false
  replace = false

# 相关文章配置
[page.related]
  enable = true
  count = 5

# 赞赏设置
[page.reward]
  enable = false
  animation = true
  position = "after"
  mode = "fixed"
  comment = "Buy me a coffee~"
  [page.reward.ways]
    wechatpay = "/images/wechatpay.jpg"
    alipay = "/images/alipay.jpg"
    # 其他支付方式可以根据需求启用
    # paypal = "/images/paypal.png"
    # bitcoin = "/images/bitcoin.png"

  # 文章页面的分享信息设置
  [page.share]
    enable = true
    Twitter = true
    Facebook = true
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = true
    Reddit = false
    VK = false
    Myspace = false
    Blogger = false
    Baidu = false
    Mix = false


# 评论系统设置
  [page.comment]
    enable = false
    # FixIt 0.2.13 | 新增 Artalk 评论系统设置 (https://artalk.js.org/)
    [page.comment.artalk]
      enable = false
      server = "https://yourdomain"
      site = "默认站点"
      # FixIt 0.3.3 | 新增 是否使用后端配置
      useBackendConf = false
      placeholder = ""
      noComment = ""
      sendBtn = ""
      editorTravel = true
      flatMode = 'auto'
      # FixIt 0.2.17 | 更改 启用 lightgallery 支持
      lightgallery = false
      locale = "" # FixIt 0.2.15 | NEW
      # FixIt 0.2.18 | NEW
      emoticons = ""
      nestMax = 2
      nestSort = "DATE_ASC" # ["DATE_ASC", "DATE_DESC", "VOTE_UP_DESC"]
      vote = true
      voteDown = false
      uaBadge = true
      listSort = true
      imgUpload = true
      preview = true
      versionCheck = true
    # Disqus 评论系统设置 (https://disqus.com/)
    [page.comment.disqus]
      enable = false
      # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
      shortname = ""
    # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
    [page.comment.gitalk]
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Valine 评论系统设置 (https://github.com/xCss/Valine)
    [page.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      placeholder = ""
      avatar = "mp"
      meta = []
      requiredFields = []
      pageSize = 10
      lang = ""
      visitor = true
      recordIP = true
      highlight = true
      enableQQ = false
      serverURLs = ""
      emoji = ""
      commentCount = true # FixIt 0.2.13 | NEW
    # # FixIt 0.2.13 | 新增 Waline 评论系统设置 (https://waline.js.org)
    [page.comment.waline]
      enable = false
      serverURL = ""
      pageview = false
      emoji = ['//unpkg.com/@waline/emojis@1.1.0/weibo']
      meta = ['nick', 'mail', 'link']
      requiredMeta = []
      login = 'enable'
      wordLimit = 0
      pageSize = 10
      imageUploader = false
      highlighter = false
      comment = false
      texRenderer = false
      search = false
      recaptchaV3Key = ""
      reaction = false
    # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
    [page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = ""
    # Telegram 评论系统设置 (https://comments.app/)
    [page.comment.telegram]
      enable = false
      siteID = ""
      limit = 5
      height = ""
      color = ""
      colorful = true
      dislikes = false
      outlined = false
    # Commento 评论系统设置 (https://commento.io/)
    [page.comment.commento]
      enable = false
    # Utterances 评论系统设置 (https://utteranc.es/)
    [page.comment.utterances]
      enable = false
      repo = ""
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"
    # # FixIt 0.2.13 | 新增 Twikoo 评论系统设置 (https://twikoo.js.org/)
    [page.comment.twikoo]
      enable = false
      envId = ""
      region = ""
      path = ""
      visitor = true
      commentCount = true
      # FixIt 0.2.17 | 更改 启用 lightgallery 支持
      lightgallery = false
      # FixIt 0.2.17 | 新增 启用 Katex 支持
      katex = false
    # FixIt 0.2.14 | 新增 Giscus 评论系统设置 (https://giscus.app/)
    [page.comment.giscus]
      enable = false
      repo = ""
      repoId = ""
      category = ""
      categoryId = ""
      mapping = ""
      strict = "0" # FixIt NEW | 0.2.18
      term = ""
      reactionsEnabled = "1"
      emitMetadata = "0"
      inputPosition = "bottom" # ["top", "bottom"]
      lightTheme = "light"
      darkTheme = "dark"
      lazyLoad = true




# 第三方库配置
  [page.library]
    [page.library.css]
      # someCSS = "some.css"
      # 位于 "assets/"
      # 或者
      # someCSS = "https://cdn.example.com/some.css"
    [page.library.js]
      # someJavascript = "some.js"
      # 位于 "assets/"
      # 或者
      # someJavascript = "https://cdn.example.com/some.js"
  # 页面 SEO 配置
  [page.seo]
    # 图片 URL
    images = []
    # 出版者信息
    [page.seo.publisher]
      name = "Lruihao"
      logoUrl = "/images/avatar.png"


# 主页的社交信息设置
[social]
  GitHub = "X"
  Twitter = ""
  Facebook = ""
  Medium = ""
  Gitlab = ""
  Bilibili = ""
  ORCID = ""
  QQ = ""
  QQGroup = "" # https://qun.qq.com/join.html
  Email = ""
  RSS = false
  # 自定义社交链接如下
  [FixItDemo]
    id = "demo.fixit"
    weight = 1000
    Template = "https://%v.lruihao.cn/"
    Title = "FixIt Demo"
    [FixItDemo.icon]
      Src = "images/icons/demo.svg"