# -------------------------------------------------------------------------------------
# Permalinks Configuration | Permalinks 配置
# See: https://gohugo.io/content-management/urls/#permalinks
# -------------------------------------------------------------------------------------

# posts = ":year/:month/:filename"
documentation = ":sections[0:]/:slugorfilename"
guides = "guides/:slugorfilename"

[page]
    posts = '/articles/:year/:month/:slug/'
    tutorials = '/training/:slug/'
[section]
    posts = '/articles/'
    tutorials = '/training/'