# -------------------------------------------------------------------------------------
# Taxonomies Configuration | 分类法配置
# See: https://gohugo.io/content-management/taxonomies/#configure-taxonomies
# -------------------------------------------------------------------------------------

 _merge = "shallow"
category = "categories"
tag = "tags"
collection = "collections"
